name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: AdityaKumarJha
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake 🐍"
          add: "dist/github-contribution-grid-snake.svg"
